### ISSUE TITLE
save @Wers200

### ISSUE THREAD

**Issue by Compdog-inc** [Wers200/tic-tac-toe-web#2]
I CANT STOP LAUGHING

_Originally posted by @Wers200 in https://github.com/Wers200/tic-tac-toe-ai/pull/1#issuecomment-922346427_

**Comment by Compdog-inc** [comment]
save him

**Comment by Compdog-inc** [comment]
quick

**Comment by Wers200** [comment]
f

**Comment by Compdog-inc** [comment]
@Wers200 died...
